version: '3.8'

services:
    app:
        build: .
        env_file: 
            - ./.env
        restart: always
        volumes:
            - .:/app
        ports:
            - 8000:8000
        command: gunicorn olmonopolet_api.wsgi -b 0.0.0.0:8000
#